# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, db_index=True, max_length=255)),
                ('uri', models.CharField(blank=True, db_index=True, max_length=255)),
                ('celex_number', models.CharField(blank=True, max_length=100)),
                ('number', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('subject', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('DC_description', models.CharField(blank=True, max_length=500)),
                ('DC_identifier', models.CharField(blank=True, max_length=500)),
                ('DC_language', models.CharField(blank=True, max_length=500)),
                ('DC_publisher', models.CharField(blank=True, max_length=500)),
                ('DC_source', models.CharField(blank=True, max_length=500)),
                ('DC_subject', models.CharField(blank=True, max_length=500)),
                ('DC_title', models.CharField(blank=True, max_length=500)),
                ('DC_type', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
