# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=255, unique=True),
        ),
    ]
