# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0002_auto_20170124_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
