# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0004_auto_20170124_1744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
