# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0005_auto_20170124_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='regulation',
            name='keywords',
            field=models.ManyToManyField(to='regulations.Keyword'),
        ),
    ]
