# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0007_auto_20170124_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
