# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0008_regulation_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(blank=True, max_length=1000)),
                ('summary', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='regulation',
            name='summary',
        ),
        migrations.AddField(
            model_name='regulation',
            name='summaries',
            field=models.ManyToManyField(to='regulations.Summery'),
        ),
    ]
