# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0009_auto_20170129_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Summery',
            new_name='Summary',
        ),
    ]
